/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSocialFeedRouteImport } from './routes/api/social-feed'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as ApiPublicHooksSocialSyncRouteImport } from './routes/api/public/hooks/social-sync'
import { Route as ApiPublicOauthProviderActionRouteImport } from './routes/api/public/oauth/$provider.$action'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSocialFeedRoute = ApiSocialFeedRouteImport.update({
  id: '/api/social-feed',
  path: '/api/social-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSocialSyncRoute =
  ApiPublicHooksSocialSyncRouteImport.update({
    id: '/api/public/hooks/social-sync',
    path: '/api/public/hooks/social-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthProviderActionRoute =
  ApiPublicOauthProviderActionRouteImport.update({
    id: '/api/public/oauth/$provider/$action',
    path: '/api/public/oauth/$provider/$action',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/social-feed': typeof ApiSocialFeedRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/api/public/hooks/social-sync': typeof ApiPublicHooksSocialSyncRoute
  '/api/public/oauth/$provider/$action': typeof ApiPublicOauthProviderActionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/social-feed': typeof ApiSocialFeedRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/api/public/hooks/social-sync': typeof ApiPublicHooksSocialSyncRoute
  '/api/public/oauth/$provider/$action': typeof ApiPublicOauthProviderActionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/social-feed': typeof ApiSocialFeedRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/api/public/hooks/social-sync': typeof ApiPublicHooksSocialSyncRoute
  '/api/public/oauth/$provider/$action': typeof ApiPublicOauthProviderActionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/social-feed'
    | '/legal/$slug'
    | '/api/public/hooks/social-sync'
    | '/api/public/oauth/$provider/$action'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/social-feed'
    | '/legal/$slug'
    | '/api/public/hooks/social-sync'
    | '/api/public/oauth/$provider/$action'
  id:
    | '__root__'
    | '/'
    | '/api/social-feed'
    | '/legal/$slug'
    | '/api/public/hooks/social-sync'
    | '/api/public/oauth/$provider/$action'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSocialFeedRoute: typeof ApiSocialFeedRoute
  LegalSlugRoute: typeof LegalSlugRoute
  ApiPublicHooksSocialSyncRoute: typeof ApiPublicHooksSocialSyncRoute
  ApiPublicOauthProviderActionRoute: typeof ApiPublicOauthProviderActionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/social-feed': {
      id: '/api/social-feed'
      path: '/api/social-feed'
      fullPath: '/api/social-feed'
      preLoaderRoute: typeof ApiSocialFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/social-sync': {
      id: '/api/public/hooks/social-sync'
      path: '/api/public/hooks/social-sync'
      fullPath: '/api/public/hooks/social-sync'
      preLoaderRoute: typeof ApiPublicHooksSocialSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/$provider/$action': {
      id: '/api/public/oauth/$provider/$action'
      path: '/api/public/oauth/$provider/$action'
      fullPath: '/api/public/oauth/$provider/$action'
      preLoaderRoute: typeof ApiPublicOauthProviderActionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSocialFeedRoute: ApiSocialFeedRoute,
  LegalSlugRoute: LegalSlugRoute,
  ApiPublicHooksSocialSyncRoute: ApiPublicHooksSocialSyncRoute,
  ApiPublicOauthProviderActionRoute: ApiPublicOauthProviderActionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
